flog/group/forms.py
"""
MIT License
Copyright (c) 2021 Andy Zhou
"""
from flask_babel import lazy_gettext as _l
from flask_wtf import FlaskForm
from wtforms import (
    StringField,
    SubmitField,
    ValidationError,
    SelectField,
    BooleanField,
    PasswordField,
)
from wtforms.validators import Length, DataRequired
from ..models import Group

dr_message = _l("Please fill out this field with valid values.")
l_message = _l("Field must be between %(min)d and %(max)d characters long.")


class GroupCreationForm(FlaskForm):
    group_name = StringField(
        _l("Group Name"), validators=[Length(max=128, message=l_message)]
    )
    private = BooleanField(_l("Private"))
    submit = SubmitField(_l("Submit"))


class GroupFindForm(FlaskForm):
    group_name = StringField(
        _l("Group Name"), validators=[DataRequired(message=dr_message)]
    )
    submit = SubmitField(_l("Submit"))

    def validate_group_name(self, field):
        if Group.query.filter_by(name=field.data).count() == 0:
            raise ValidationError(_l("No such group"))


class GroupInviteForm(FlaskForm):
    group_id = SelectField(_l("Group Name"), coerce=int)
    submit = SubmitField(_l("Submit"))

    def validate_group_id(self, field):
        if Group.query.get(field.data) is None:
            raise ValidationError(_l("No such group"))


class ManagerConfirmForm(FlaskForm):
    password = PasswordField(
        _l("Password"), validators=[DataRequired(message=dr_message)]
    )
    submit = SubmitField(_l("Submit"))

flog/user/forms.py
"""
MIT License
Copyright (c) 2020 Andy Zhou
"""
from flask_wtf import FlaskForm
from flask_babel import lazy_gettext as _l
from wtforms import StringField, TextAreaField, SubmitField, PasswordField
from wtforms.validators import (
    Length,
    EqualTo,
    Email,
    ValidationError,
    URL,
    DataRequired,
    Regexp,
)
from ..models import User

# l_message is short for 'length_message'
l_message = _l("Field must be between %(min)d and %(max)d characters long.")
e_message = _l("Invalid email.")
u_message = _l("Invalid url.")


class EditProfileForm(FlaskForm):
    username = StringField(
        _l("Username"),
        validators=[
            Length(0, 32),
            Regexp(
                r"^([A-Za-z][A-Za-z0-9_\-.])*$",
                0,
                _l(
                    "Usernames must have only letters, numbers, dots, underscores or dashes"
                ),
            ),
        ],
    )
    name = StringField(_l("Real Name"), validators=[Length(0, 64, l_message)])
    location = StringField(_l("Location"), validators=[Length(0, 64, l_message)])
    about_me = TextAreaField(_l("About me"), validators=[Length(0, 300, l_message)])
    custom_avatar_url = StringField(_l("Avatar URL"), validators=[URL(True, u_message)])
    submit = SubmitField(_l("Submit"))


class PasswordChangeForm(FlaskForm):
    password = PasswordField(_l("New Password"))
    password_again = PasswordField(
        _l("Again"), validators=[EqualTo("password", _l("Passwords must match"))]
    )
    submit = SubmitField(_l("Submit"))


class ValidateEmailForm(FlaskForm):
    email = StringField(_l("Email"), validators=[Email(message=e_message)])
    submit = SubmitField(_l("Submit"))

    def validate_email(self, field):
        if User.query.filter_by(email=field.data).count() == 0:
            raise ValidationError(e_message)

flog/group/__init__.py
"""
MIT License
Copyright (c) 2021 Andy Zhou
"""
from flask import Blueprint

group_bp = Blueprint("group", __name__)

from . import views

flog/group/views.py
"""
MIT License
Copyright (c) 2021 Andy Zhou
"""
from flask import render_template, flash, abort, request
from flask_babel import _
from flask_login import login_required, current_user
from . import group_bp
from .forms import GroupCreationForm, GroupFindForm, GroupInviteForm, ManagerConfirmForm
from ..models import db, Group, User, Message
from ..utils import redirect_back
from ..notifications import (
    push_group_join_notification,
    push_group_invite_notification,
    push_new_message_notification,
)


@group_bp.route("/all/")
@login_required
def all():
    groups = Group.query.filter(~Group.private).all()
    if current_user.is_administrator():
        groups = Group.query.all()
    return render_template("user/groups.html", groups=groups)


@group_bp.route("/create/", methods=["GET", "POST"])
@login_required
def create():
    form = GroupCreationForm()
    if form.validate_on_submit():
        group = Group(name=form.group_name.data, private=form.private.data)
        current_user.join_group(group)
        group.manager = current_user
        db.session.commit()
        flash(_("Created group %(name)s", name=group.name))
        return redirect_back()
    return render_template("group/create.html", form=form)


@group_bp.route("/find/", methods=["GET", "POST"])
@login_required
def explore():
    form = GroupFindForm()
    if form.validate_on_submit():
        group = Group.query.filter_by(name=form.group_name.data).first_or_404()
        push_group_join_notification(
            joiner=current_user, group=group, receiver=group.manager
        )
        flash(
            _(
                """We have sent a notification to the manager of the group.
                All you should do is to wait the manager's reply."""
            )
        )
        return redirect_back()
    return render_template("group/find.html", form=form)


@group_bp.route("/join/<token>/")
@login_required
def join(token):
    group = Group.verify_join_token(token)
    if group is None:
        abort(404)
    else:
        user_id = request.args.get("user_id", type=int)
        if user_id is None:
            user = current_user
        else:
            user = User.query.get(user_id)
        user.join_group(group)
        flash(_("Joined group %(name)s", name=group.name))
        return redirect_back()


@group_bp.route("/invite/<int:user_id>/", methods=["GET", "POST"])
@login_required
def invite_user(user_id: int):
    form = GroupInviteForm()
    form.group_id.choices = [
        (g.id, g.name)
        for g in Group.query.filter_by(manager=current_user).order_by("name")
    ]
    if len(form.group_id.choices) == 0:
        flash(
            _(
                """
            You are not managing any groups.
            Please create a group first to invite other users.
        """
            )
        )
        return redirect_back()
    if form.validate_on_submit():
        group = Group.query.get_or_404(form.group_id.data)
        invited_user = User.query.get_or_404(user_id)
        push_group_invite_notification(current_user, invited_user, group)
        flash(
            _("Notification sent to user %(username)s", username=invited_user.username)
        )
        return redirect_back()
    return render_template("group/invite.html", form=form)


@group_bp.route("/<int:id>/info/", methods=["GET", "POST"])
@login_required
def info(id: int):
    group = Group.query.get_or_404(id)
    if group.private and current_user not in group.members:
        abort(403)
    return render_template("group/info.html", group=group)


@group_bp.route("/<int:id>/discussion/", methods=["GET", "POST"])
@login_required
def discussion(id: int):
    group = Group.query.get_or_404(id)
    if current_user not in group.members:
        abort(403)
    if request.method == "POST":
        body = request.form.get("body")
        message = Message(author=current_user, body=body)
        group.messages.append(message)
        db.session.commit()
        for member in group.members:
            if member != current_user:
                push_new_message_notification(current_user, member, group)
    return render_template("group/discussion.html", group=group)


@group_bp.route("/<int:group_id>/kick/<int:user_id>/", methods=["POST"])
@login_required
def kick_out(group_id: int, user_id: int):
    group = Group.query.get_or_404(group_id)
    if current_user != group.manager:
        abort(403)
    user = User.query.get_or_404(user_id)
    group.members.remove(user)
    db.session.commit()
    return redirect_back()


@group_bp.route("/<int:group_id>/set-manager/<int:user_id>/", methods=["GET", "POST"])
@login_required
def set_manager(group_id: int, user_id: int):
    group = Group.query.get_or_404(group_id)
    if current_user != group.manager:
        abort(403)
    form = ManagerConfirmForm()
    if form.validate_on_submit():
        if not current_user.verify_password(form.password.data):
            abort(403)
        user = User.query.get_or_404(user_id)
        group.manager = user
        db.session.commit()
        return redirect_back()
    return render_template("group/set_manager.html", form=form)

flog/user/__init__.py
"""
MIT License
Copyright (c) 2020 Andy Zhou
"""
from flask import Blueprint

user_bp = Blueprint("user", __name__)

from . import views

flog/user/views.py
"""
MIT License
Copyright (c) 2021 Andy Zhou
"""
from flask import render_template, redirect, url_for, flash, request, current_app
from flask_login import current_user, login_required, login_user
from flask_babel import _
from . import user_bp
from .forms import (
    EditProfileForm,
    PasswordChangeForm,
    ValidateEmailForm,
)
from ..models import db, User, Permission
from ..decorators import permission_required
from ..utils import redirect_back
from ..notifications import (
    push_follow_notification,
)
from ..emails import send_email


@user_bp.route("/profile/edit/", methods=["GET", "POST"])
@login_required
def edit_profile():
    if current_user.is_administrator():
        return redirect(url_for("admin.edit_profile", id=current_user.id))
    form = EditProfileForm()
    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.name = form.name.data
        current_user.location = form.location.data
        current_user.about_me = form.about_me.data
        current_user.custom_avatar_url = form.custom_avatar_url.data
        db.session.add(current_user._get_current_object())
        db.session.commit()
        flash(_("Your profile has been updated!"), "success")
        return redirect(url_for("main.main"))
    form.username.data = current_user.username
    form.name.data = current_user.name
    form.location.data = current_user.location
    form.about_me.data = current_user.about_me
    return render_template("user/edit_profile.html", form=form)


@user_bp.route("/follow/<username>/", methods=["POST"])
@login_required
@permission_required(Permission.FOLLOW)
def follow(username):
    user = User.query.filter_by(username=username).first_or_404()
    if current_user.is_following(user):
        flash(_("Already followed."), "info")
        return redirect_back()
    current_user.follow(user)
    push_follow_notification(follower=current_user, receiver=user)
    flash(_("User followed."), "success")
    return redirect_back()


@user_bp.route("/unfollow/<username>/", methods=["POST"])
@login_required
@permission_required(Permission.FOLLOW)
def unfollow(username):
    user = User.query.filter_by(username=username).first()
    if not current_user.is_following(user):
        flash(_("Not following yet."), "info")
        return redirect_back()
    current_user.unfollow(user)
    flash(_("User unfollowed."), "info")
    return redirect_back()


@user_bp.route("/user/<username>/")
def profile(username):
    user = User.query.filter_by(username=username).first_or_404()
    return render_template("user/user_profile.html", user=user)


@user_bp.route("/user/<username>/followers/")
def followers(username):
    user = User.query.filter_by(username=username).first_or_404()
    page = request.args.get("page", 1, type=int)
    pagination = user.followers.paginate(
        page, per_page=current_app.config["USERS_PER_PAGE"]
    )
    return render_template("user/followers.html", pagination=pagination, user=user)


@user_bp.route("/user/all/")
def all():
    page = request.args.get("page", 1, type=int)
    pagination = User.query.order_by(User.id.desc()).paginate(
        page, per_page=current_app.config["USERS_PER_PAGE"]
    )
    user_count = User.query.count()
    return render_template(
        "user/all.html", pagination=pagination, user_count=user_count
    )


@user_bp.route("/password/change/", methods=["GET", "POST"])
@login_required
def change_password():
    form = PasswordChangeForm()
    if form.validate_on_submit():
        current_user.set_password(form.password.data)
        flash(_("Password Changed"))
        return redirect(url_for("user.profile", username=current_user.username))
    return render_template("user/change_password.html", form=form)


@user_bp.route("/password/forget/", methods=["GET", "POST"])
def forget_password():
    form = ValidateEmailForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        token = user.generate_confirmation_token()
        send_email(
            [user.email],
            "Reset Password",
            "/user/email/reset_password",
            user=user,
            token=token,
        )
        flash(_("A confirmation email has been sent."))
        return redirect(url_for("user.forget_password"))
    return render_template("user/forget_password.html", form=form)


@user_bp.route("/password/reset/<token>/", methods=["GET", "POST"])
def reset_password(token):
    user = User.from_confirmation_token(token)
    form = PasswordChangeForm()
    if form.validate_on_submit():
        user.set_password(form.password.data)
        login_user(user)
        flash(_("Password Changed"))
        return redirect(url_for("main.main"))
    return render_template("user/change_password.html", form=form)


@user_bp.route("/groups/")
def groups():
    return render_template("user/groups.html", groups=current_user.groups)

flog/templates/user/all.html
{#
Copyright (c) 2020 Andy Zhou
MIT License
#}
{% extends 'base.html' %}
{% from 'bootstrap/pagination.html' import render_pagination %}
{% from 'macros.html' import user_card with context %}
{% block title %}{{ _("All users") }} {% endblock %}
{% block page_content %}
<div class="row">
    <div class="col-lg-8">
        <ul class="list-group">
            {% for user in pagination.items %}
                {{ user_card(user) }}
            {% endfor %}
        </ul>
    </div>
    {% include 'main/_sidebar.html' %}
    {{ render_pagination(pagination) }}
    {% if current_app.testing %}
        <p style="display: none">{{ user_count }}</p>
    {% endif %}
</div>
{% endblock page_content %}

flog/templates/user/change_password.html
{% extends 'base.html' %}
{% from 'bootstrap/form.html' import render_form %}
{% block page_content %}
    <h1>{{ _("Change Password") }}</h1>
    {{ render_form(form) }}
{% endblock page_content %}

flog/templates/user/edit_profile.html
{#
Copyright (c) 2020 Andy Zhou
MIT License
#}
{% extends 'base.html' %}
{% from 'bootstrap/form.html' import render_form %}
{% block title %}{{ _("Edit Profile") }}{% endblock title %}
{% block page_content %}
    <h1 class="display-3">{{ _("Edit Profile") }}</h1>
    {{ render_form(form) }}
{% endblock page_content %}

flog/templates/user/followers.html
{#
Copyright (c) 2020 Andy Zhou
MIT License
#}
{% extends 'base.html' %}
{% from 'macros.html' import user_card with context %}
{% from 'bootstrap/pagination.html' import render_pagination %}
{% block title %}
    {% if user == current_user %} {{ _("Your") }}
    {% else %} {{ _("His or her") }}
    {% endif %} {{ _("followers") }}
{% endblock %}
{% block page_content %}
    <ul class="list-group">
        {% if pagination.items | length > 1 %}
        {% for follow in pagination.items %}
            {% if follow.follower != user %}
                {{ user_card(follow.follower) }}
            {% endif %}
        {% endfor %}
        {% else %}
            <div class="tip">
                {% if user == current_user %}
                    <h3>{{ _("You have no followers") }}</h3>
                {% else %}
                    <h3>{{ _('User %s has no followers' % user.username) }}</h3>
                {% endif %}
            </div>
        {% endif %}
    </ul>
    {% if pagination.items | length != 1 %}
        {{ render_pagination(pagination) }}
    {% endif %}
{% endblock page_content %}

flog/templates/user/forget_password.html
{% from 'bootstrap/form.html' import render_form %}
{% extends 'base.html' %}
{% block page_content %}
    <h1>{{ _("Forget password") }}</h1>
    {{ render_form(form) }}
{% endblock page_content %}

flog/templates/user/groups.html
{#
Copyright (c) 2021 Andy Zhou
MIT License
#}
{% extends 'base.html' %}
{% from 'macros.html' import group_card with context %}
{% block title %}{{ _("Groups") }} {% endblock %}
{% block page_content %}
    <div class="row">
        <div class="col-md-8">
            <ul class="list-group">
                {% for group in groups %}
                    {{ group_card(group) }}
                {% endfor %}
            </ul>
        </div>
        {% include 'main/_sidebar.html' %}
    </div>
{% endblock page_content %}

flog/templates/user/user_profile.html
{% extends 'base.html' %}
{% from 'macros.html' import render_user_role, follow_area, static_file, level_badge with context %}
{% set locale = 'en_US' if not current_user.locale else current_user.locale %}
{% block title %}
    Flog - {{ user.username }}
{% endblock title %}
{% block page_content %}
<div class="row container">
    <div class="col-lg-2">
        <img class="img-fluid" src="{{ user.avatar_url() }}" width="200px" height="200px">
    </div>
    <div class="col-lg-10">
        <h1>
            {{ render_user_role(user) }}
            {{ level_badge(user) }}
        </h1>
        {% if current_user.can(Permission.MODERATE) or user == current_user %}
            <div class="d-flex">
                <div class="mr-2">{{ static_file("svg", "svg/pi-empty.svg", width=20, height=20) }}</div>
                <div>{{ user.coins | round(2) }}</div>
            </div>
            <div class="d-flex">
                <div id="current-level-full">
                    <div id="current-level-progress" data-experience="{{ user.experience }}" data-level="{{ user.level() }}">
                    </div>
                </div>
            </div>
        {% endif %}
        {% if user.name or user.location %}
        <p>
            {% if user.name and current_user.can(Permission.MODERATE) %}{{ user.name }}{% endif %}
            {% if user.location %}
                {{ _("from") }} <a href="http://bing.com/maps/?q={{ user.location }}">
                    {{ user.location }}
                </a>
            {% endif %}
        </p>
        {% endif %}

        {% if current_user.is_administrator() %}
            <p><a href="mailto:{{ user.email }}">{{ user.email }}</a></p>
            {% if not user.confirmed -%}<p>{{ _("This email hasn't been confirmed yet.") }}</p>{%- endif %}
        {% endif %}
        {% if user.about_me %}<p>{{ user.about_me }}</p>{% endif %}

        <p>
            {% if user.member_since %}
            {{ _("Member since") }} {{ moment(user.member_since).format('L') }}
            {% endif %}
            {% if user.last_seen %}
            {{ _('Last seen') }} {{ moment(user.last_seen).fromNow() }}
            {% endif %}
        </p>
        {{ follow_area(user) }}
        <p>
            {% if user != current_user %} {{ _("This user has") }}
            {% else %}{{ _("You have") }}
            {% endif %}{{ ngettext('%(num)s follower', '%(num)s followers', __num=user.followers.count()-1) }}
        </p>
        {% if user == current_user and not current_user.is_administrator() %}
            <a class="btn btn-outline-primary" href="{{ url_for('user.edit_profile', id=user.id) }}">
                {{ _("Edit Profile") }}
            </a>
        {% elif current_user.is_administrator() %}
            <a class="btn btn-outline-danger" href="{{ url_for('admin.edit_profile', id=user.id) }}">
                {{ _("Edit Profile [Admin]") }}
            </a>
        {% endif %}
        <a class="btn btn-outline-primary" href="{{ url_for('group.invite_user', user_id=user.id) }}">
            {{ _("Invite this user to your group.") }}
        </a>
    </div>
</div>
{% endblock page_content %}