flog/group/forms.py
"""
MIT License
Copyright (c) 2021 Andy Zhou
"""
from flask_babel import lazy_gettext as _l
from flask_wtf import FlaskForm
from wtforms import (
    StringField,
    SubmitField,
    ValidationError,
    SelectField,
    BooleanField,
    PasswordField,
)
from wtforms.validators import Length, DataRequired
from ..models import Group

dr_message = _l("Please fill out this field with valid values.")
l_message = _l("Field must be between %(min)d and %(max)d characters long.")


class GroupCreationForm(FlaskForm):
    group_name = StringField(
        _l("Group Name"), validators=[Length(max=128, message=l_message)]
    )
    private = BooleanField(_l("Private"))
    submit = SubmitField(_l("Submit"))


class GroupFindForm(FlaskForm):
    group_name = StringField(
        _l("Group Name"), validators=[DataRequired(message=dr_message)]
    )
    submit = SubmitField(_l("Submit"))

    def validate_group_name(self, field):
        if Group.query.filter_by(name=field.data).count() == 0:
            raise ValidationError(_l("No such group"))


class GroupInviteForm(FlaskForm):
    group_id = SelectField(_l("Group Name"), coerce=int)
    submit = SubmitField(_l("Submit"))

    def validate_group_id(self, field):
        if Group.query.get(field.data) is None:
            raise ValidationError(_l("No such group"))


class ManagerConfirmForm(FlaskForm):
    password = PasswordField(
        _l("Password"), validators=[DataRequired(message=dr_message)]
    )
    submit = SubmitField(_l("Submit"))

flog/group/__init__.py
"""
MIT License
Copyright (c) 2021 Andy Zhou
"""
from flask import Blueprint

group_bp = Blueprint("group", __name__)

from . import views

flog/group/views.py
"""
MIT License
Copyright (c) 2021 Andy Zhou
"""
from flask import render_template, flash, abort, request
from flask_babel import _
from flask_login import login_required, current_user
from . import group_bp
from .forms import GroupCreationForm, GroupFindForm, GroupInviteForm, ManagerConfirmForm
from ..models import db, Group, User, Message
from ..utils import redirect_back
from ..notifications import (
    push_group_join_notification,
    push_group_invite_notification,
    push_new_message_notification,
)


@group_bp.route("/all/")
@login_required
def all():
    groups = Group.query.filter(~Group.private).all()
    if current_user.is_administrator():
        groups = Group.query.all()
    return render_template("user/groups.html", groups=groups)


@group_bp.route("/create/", methods=["GET", "POST"])
@login_required
def create():
    form = GroupCreationForm()
    if form.validate_on_submit():
        group = Group(name=form.group_name.data, private=form.private.data)
        current_user.join_group(group)
        group.manager = current_user
        db.session.commit()
        flash(_("Created group %(name)s", name=group.name))
        return redirect_back()
    return render_template("group/create.html", form=form)


@group_bp.route("/find/", methods=["GET", "POST"])
@login_required
def explore():
    form = GroupFindForm()
    if form.validate_on_submit():
        group = Group.query.filter_by(name=form.group_name.data).first_or_404()
        push_group_join_notification(
            joiner=current_user, group=group, receiver=group.manager
        )
        flash(
            _(
                """We have sent a notification to the manager of the group.
                All you should do is to wait the manager's reply."""
            )
        )
        return redirect_back()
    return render_template("group/find.html", form=form)


@group_bp.route("/join/<token>/")
@login_required
def join(token):
    group = Group.verify_join_token(token)
    if group is None:
        abort(404)
    else:
        user_id = request.args.get("user_id", type=int)
        if user_id is None:
            user = current_user
        else:
            user = User.query.get(user_id)
        user.join_group(group)
        flash(_("Joined group %(name)s", name=group.name))
        return redirect_back()


@group_bp.route("/invite/<int:user_id>/", methods=["GET", "POST"])
@login_required
def invite_user(user_id: int):
    form = GroupInviteForm()
    form.group_id.choices = [
        (g.id, g.name)
        for g in Group.query.filter_by(manager=current_user).order_by("name")
    ]
    if len(form.group_id.choices) == 0:
        flash(
            _(
                """
            You are not managing any groups.
            Please create a group first to invite other users.
        """
            )
        )
        return redirect_back()
    if form.validate_on_submit():
        group = Group.query.get_or_404(form.group_id.data)
        invited_user = User.query.get_or_404(user_id)
        push_group_invite_notification(current_user, invited_user, group)
        flash(
            _("Notification sent to user %(username)s", username=invited_user.username)
        )
        return redirect_back()
    return render_template("group/invite.html", form=form)


@group_bp.route("/<int:id>/info/", methods=["GET", "POST"])
@login_required
def info(id: int):
    group = Group.query.get_or_404(id)
    if group.private and current_user not in group.members:
        abort(403)
    return render_template("group/info.html", group=group)


@group_bp.route("/<int:id>/discussion/", methods=["GET", "POST"])
@login_required
def discussion(id: int):
    group = Group.query.get_or_404(id)
    if current_user not in group.members:
        abort(403)
    if request.method == "POST":
        body = request.form.get("body")
        message = Message(author=current_user, body=body)
        group.messages.append(message)
        db.session.commit()
        for member in group.members:
            if member != current_user:
                push_new_message_notification(current_user, member, group)
    return render_template("group/discussion.html", group=group)


@group_bp.route("/<int:group_id>/kick/<int:user_id>/", methods=["POST"])
@login_required
def kick_out(group_id: int, user_id: int):
    group = Group.query.get_or_404(group_id)
    if current_user != group.manager:
        abort(403)
    user = User.query.get_or_404(user_id)
    group.members.remove(user)
    db.session.commit()
    return redirect_back()


@group_bp.route("/<int:group_id>/set-manager/<int:user_id>/", methods=["GET", "POST"])
@login_required
def set_manager(group_id: int, user_id: int):
    group = Group.query.get_or_404(group_id)
    if current_user != group.manager:
        abort(403)
    form = ManagerConfirmForm()
    if form.validate_on_submit():
        if not current_user.verify_password(form.password.data):
            abort(403)
        user = User.query.get_or_404(user_id)
        group.manager = user
        db.session.commit()
        return redirect_back()
    return render_template("group/set_manager.html", form=form)

flog/templates/group/all.html
{% extends 'base.html' %}
{% from 'macros.html' import group_card with context %}
{% block title %}
    All public groups
{% endblock %}
{% block content %}
    <div class="list-group">
        {% for group in groups %}
            {{ group_card(group) }}
        {% endfor %}
    </div>
{% endblock %}

flog/templates/group/create.html
{% extends 'base.html' %}
{% from 'bootstrap/form.html' import render_form %}
{% block page_content %}
    <h1 class="display-3">{{ _("Create a group") }}</h1>
    {{ render_form(form) }}
{% endblock page_content %}

flog/templates/group/discussion.html
{% extends 'base.html' %}
{% from 'macros.html' import user_card, message_card, static_file with context %}
{% block title %} Group: {{ group.name }} {% endblock %}
{% block page_content %}
    <h2>{{ group.name }}{{ _("'s chatting room") }}</h2>
    <hr>
    <div class="messages">
        {% for message in group.messages %}
            {{ message_card(message) }}
        {% endfor %}
    </div>
    <form style="width: 100%" class="form-inline d-flex" method="POST">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
        <input type="text" name="body" class="form-control btn-block flex-grow-1" required>
        <input type="submit" name="submit" class="form-control btn btn-success" value="{{ _('Send') }}">
    </form>
    <button id="back-to-top" class="btn" style="display: none">
        <i class="bi-arrow-up"></i><br>
    </button>
{% endblock page_content %}
{% block scripts %}
    {{ super() }}
    {{ static_file('js', 'js/discussion.js') }}
{% endblock scripts %}

flog/templates/group/find.html
{% extends 'base.html' %}
{% from 'bootstrap/form.html' import render_form %}
{% block scripts %}
    {{ super() }}
    <script>
        $(document).ready(function () {
            let element = $("input[name='group_name']");
            let hint_element = $("<div id='hint'>" + "{{ _("Hint") }}" + ":</div>");
            element.after(hint_element);
            element.keyup(function (){
                let value = element.val();
                console.log("{{ url_for('ajax.get_group_hint') }}"+ "?q=" + value);
                $.get("{{ url_for('ajax.get_group_hint') }}" + "?q=" + value, function (data, status) {
                    $('#hint').html(" {{ _("Hint") }}: ");
                    let hint_list = data["hint"];
                    for(let i = 0; i < hint_list.length; i++){
                        $('#hint').html($('#hint').html() + '<br>' + hint_list[i]);
                    }
                })
            })
        })
    </script>
{% endblock scripts %}
{% block page_content %}
    <h1>{{ _("Which group do you want to join?") }}</h1>
    {{ render_form(form) }}
{% endblock page_content %}

flog/templates/group/info.html
{% extends 'base.html' %}
{% from 'macros.html' import user_card with context %}
{% block title %} Group: {{ group.name }} {% endblock %}
{% block page_content %}
    <div id="info">
        <h1>{{ group.name }}</h1>
        <h2>{{ _("Members") }} ({{ group.members | length }}): </h2>
        <ul class="list-group">
            {% for member in group.members %}
                {{ user_card(member, group=group) }}
            {% endfor %}
        </ul>
        {% if current_user in group.members %}
            <a href="{{ url_for('group.discussion', id=group.id) }}" class="btn btn-block btn-outline-primary">
                Go to discussion
            </a>
        {% endif %}
    </div>
{% endblock page_content %}

flog/templates/group/invite.html
{% extends 'base.html' %}
{% from 'bootstrap/form.html' import render_form %}
{% block page_content %}
    <h1 class="display-3">{{ _("Invite user to your group") }}</h1>
    {{ render_form(form) }}
{% endblock page_content %}

flog/templates/group/set_manager.html
{% extends 'base.html' %}
{% from 'bootstrap/form.html' import render_form %}
{% block page_content %}
    <h1>{{ _("Confirm your password to continue") }}</h1>
    {{ render_form(form) }}
{% endblock page_content %}