flog/main/forms.py
"""
MIT License
Copyright(c) 2021 Andy Zhou
"""
from flask import Markup
from flask_wtf import FlaskForm
from flask_babel import lazy_gettext as _l
from wtforms import (
    StringField,
    SubmitField,
    BooleanField,
    SelectMultipleField,
)
from wtforms.validators import DataRequired, Length
from flask_ckeditor import CKEditorField


# dr_message means data_required_message
dr_message = _l("Please fill out this field with valid values.")
l_message = _l("Field must be between %(min)d and %(max)d characters long.")


class PostForm(FlaskForm):
    title = StringField(_l("Title"), validators=[DataRequired(dr_message)])
    content = CKEditorField(_l("Content"), validators=[DataRequired(dr_message)])
    private = BooleanField(_l("Private"))
    # fmt: off
    columns = SelectMultipleField(
        Markup(_l("""
            Columns to add this post to (this field is optional)<br>
            Tip: You might need to <kbd>Ctrl</kbd> + &lt;Mouse Click&gt; to select the columns
            you want the post to be added to. If you have not created a column yet,
            you can go to <a href="/form/create/">this page</a> to create one.
            """)),
        coerce=int,
    )
    # fmt: on
    submit = SubmitField(_l("Submit"))


class CommentForm(FlaskForm):
    body = CKEditorField("", validators=[DataRequired(dr_message)])
    submit = SubmitField(_l("Comment"))


class ColumnForm(FlaskForm):
    name = StringField(
        _l("Column Name"),
        validators=[DataRequired(dr_message), Length(0, 128, l_message)],
    )
    posts = SelectMultipleField(_l("Posts to add (optional)"), coerce=int)
    submit = SubmitField(_l("Submit"))

flog/main/__init__.py
"""
MIT License
Copyright(c) 2021 Andy Zhou
"""
from flask import Blueprint

main_bp = Blueprint("main", __name__)

from . import views

flog/main/views.py
"""
MIT License
Copyright(c) 2021 Andy Zhou
"""
from datetime import datetime
from flask import (
    render_template,
    redirect,
    url_for,
    flash,
    abort,
    request,
    current_app,
)
from flask_babel import _
from flask_login import current_user, login_required
from flog.decorators import permission_required
from flog.extensions import csrf

# User and Group are necessary for line 328
from ..models import Permission, db, Post, Comment, User, Group, Column
from ..utils import redirect_back, clean_html
from ..notifications import (
    push_coin_notification,
    push_collect_notification,
    push_comment_notification,
)
from .forms import ColumnForm, PostForm, CommentForm
from . import main_bp


@main_bp.route("/")
def main():
    if not (current_user.is_authenticated or request.args.get("force", False)):
        return render_template("main/not_authorized.html")
    page = request.args.get("page", 1, type=int)
    if current_user.is_administrator():
        pagination = Post.query.order_by(Post.timestamp.desc()).paginate(
            page, per_page=current_app.config["POSTS_PER_PAGE"]
        )
    else:
        pagination = (
            Post.query.filter(~Post.private)
            .order_by(Post.timestamp.desc())
            .paginate(page, per_page=current_app.config["POSTS_PER_PAGE"])
        )
    posts = pagination.items
    return render_template("main/main.html", pagination=pagination, posts=posts)


@main_bp.route("/write/", endpoint="write", methods=["GET", "POST"])
@login_required
@permission_required(Permission.WRITE)
def create_post():
    current_app.config["CKEDITOR_PKG_TYPE"] = "standard"
    form = PostForm()
    form.columns.choices = [
        (column.id, column.name)
        for column in Column.query.filter_by(author=current_user).all()
    ]
    if form.validate_on_submit():
        cleaned_content = clean_html(form.content.data)
        post = Post(
            author=current_user,
            title=form.title.data,
            content=cleaned_content,
            private=form.private.data,
        )
        post.columns += [Column.query.get(column_id) for column_id in form.columns.data]
        if not post.private:
            current_user.experience += 5
        db.session.add(post)
        # Add the post to the database.
        db.session.commit()
        current_app.logger.info(f"{str(post)} is added.")
        flash(_("Your post has been added"), "success")
        return redirect(url_for(".full_post", id=post.id))
    return render_template("main/new_post.html", form=form)


@main_bp.route("/post/<int:id>/", methods=["GET", "POST"])
def full_post(id: int):
    current_app.config["CKEDITOR_PKG_TYPE"] = "basic"
    post = Post.query.get_or_404(id)
    if (
        (not post.private)
        or post.author == current_user
        or current_user.is_administrator()
    ):
        page = request.args.get("page", 1, type=int)
        per_page = current_app.config["COMMENTS_PER_PAGE"]
        pagination = (
            Comment.query.with_parent(post)
            .order_by(Comment.timestamp.asc())
            .paginate(page, per_page)
        )
        form = CommentForm()

        if form.validate_on_submit():
            if not current_user.can(Permission.COMMENT):
                flash(_("Blocked users cannot post a comment!"))
                return redirect_back()
            if post.private:
                flash(_("You cannot comment a private post!"))
                return redirect_back()
            comment = Comment(
                author=current_user,
                post=post,
                body=clean_html(form.body.data),
            )
            replied_id = request.args.get("reply")
            if replied_id:
                replied_comment = Comment.query.get_or_404(replied_id)
                comment.replied = replied_comment
                push_comment_notification(
                    comment=replied_comment, receiver=replied_comment.author
                )
            db.session.add(comment)
            db.session.commit()
            if post.author is not None and post.author != current_user:
                push_comment_notification(comment=comment, receiver=post.author)
            flash(_("Comment published!"), "success")
            return redirect(url_for("main.full_post", id=post.id))

        kwargs = dict(
            post=post,
            pagination=pagination,
            comments=Comment.query.with_parent(post).all(),
            form=form,
        )
        replied_id = request.args.get("reply")
        if replied_id:
            replied_comment = Comment.query.get_or_404(replied_id)
            kwargs["replied_comment"] = replied_comment
        return render_template("main/full_post.html", **kwargs)
    else:
        flash(_("The author has set this post to invisible."))
        return redirect_back()


@main_bp.route("/reply/comment/<int:comment_id>/")
@login_required
@permission_required(Permission.COMMENT)
def reply_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    return redirect(
        url_for("main.full_post", id=comment.post.id, reply=comment_id)
        + "#reply-comment-form"
    )


@main_bp.route("/comment/delete/<int:comment_id>/", methods=["POST"])
@login_required
@permission_required(Permission.COMMENT)
def delete_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    comment.delete()
    return redirect_back()


@main_bp.route("/post/manage/")
@login_required
@permission_required(Permission.WRITE)
def manage_posts():
    page = request.args.get("page", 1, type=int)
    pagination = (
        Post.query.filter_by(author=current_user)
        .order_by(Post.timestamp.desc())
        .paginate(page, per_page=current_app.config["POSTS_PER_PAGE"], error_out=False)
    )
    return render_template("main/personal_posts.html", pagination=pagination)


@main_bp.route("/post/delete/<int:id>/", methods=["POST"])
@login_required
@permission_required(Permission.WRITE)
def delete_post(id):
    post = Post.query.get(id)
    if not (current_user.is_administrator() or current_user == post.author):
        abort(403)
    post.delete()
    flash(_("Post id %(id)d deleted", id=id), "success")
    post_str = str(post)
    current_app.logger.info(f"{post_str} deleted.")
    return redirect(url_for("main.main"))


@main_bp.route("/post/edit/<int:id>/", methods=["GET", "POST"])
@login_required
@permission_required(Permission.WRITE)
def edit_post(id):
    current_app.config["CKEDITOR_PKG_TYPE"] = "standard"
    post = Post.query.get(id)
    if not (current_user.is_administrator() or current_user == post.author):
        abort(403)
    form = PostForm()
    form.columns.choices = [(column.id, column.name) for column in current_user.columns]
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        post.timestamp = datetime.utcnow()
        post.private = form.private.data
        post.columns += [Column.query.get(col_id) for col_id in form.columns.data]
        db.session.commit()
        current_app.logger.info(f"Post id {id} editted.")
        flash(_("Edit Succeeded!"), "success")
        return redirect(url_for("main.main"))
    form.title.data = post.title
    form.content.data = post.content
    form.private.data = post.private
    return render_template("main/edit_post.html", form=form)


@main_bp.route("/post/collect/<int:id>/")
@login_required
def collect_post(id):
    post = Post.query.get(id)
    if (
        not post.private
        and post.author != current_user
        and not current_user.is_collecting(post)
    ):
        current_user.collect(post)
        push_collect_notification(
            collector=current_user,
            post=post,
            receiver=post.author,
        )
        flash(_("Post collected."), "success")
    elif current_user.is_collecting(post):
        flash(_("Already collected."))
    elif post.author == current_user:
        flash(_("You cannot collect your own post."))
    else:
        flash(
            _(
                "The author has set this post to invisible. So you cannot collect this post."
            )
        )
    return redirect_back()


@main_bp.route("/post/uncollect/<int:id>/")
@login_required
def uncollect_post(id: int):
    post = Post.query.get_or_404(id)
    current_user.uncollect(post)
    flash(_("Post uncollected."), "info")
    return redirect_back()


@main_bp.route("/post/pick/<int:id>/", methods=["POST"])
@permission_required(Permission.MODERATE)
def pick(id: int):
    post = Post.query.get_or_404(id)
    if not post.picked:
        post.picked = True
        db.session.commit()
        if post.author:
            post.author.experience += 20
        flash(_("Picked post %(id)d", id=id))
    return redirect_back()


@main_bp.route("/post/unpick/<int:id>/", methods=["POST"])
@permission_required(Permission.MODERATE)
def unpick(id: int):
    post = Post.query.get_or_404(id)
    if post.picked:
        post.picked = False
        db.session.commit()
        if post.author:
            post.author.experience -= 20
        flash(_("Unpicked post %(id)d", id=id))
    return redirect_back()


@main_bp.route("/post/collected/")
@login_required
def collected_posts():
    # Get current user's collection
    posts = [post for post in Post.query.all() if current_user.is_collecting(post)]
    return render_template("main/collections.html", posts=posts)


@main_bp.route("/post/picks/")
@login_required
def picks():
    posts = Post.query.filter_by(picked=True).all()
    return render_template("main/picked.html", posts=posts)


@main_bp.route("/post/coin/<int:post_id>/", methods=["POST"])
@login_required
@csrf.exempt
def coin_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post in current_user.coined_posts:  # pragma: no cover
        abort(400)
    coins = request.form.get("coins", type=int)

flog/notification/__init__.py
"""
MIT License
Copyright(c) 2021 Andy Zhou
"""
from flask import Blueprint

notification_bp = Blueprint("notification", __name__)

from . import views

flog/notification/views.py
"""
MIT License
Copyright(c) 2021 Andy Zhou
"""
from flask import request, current_app, render_template, flash, abort
from flask_babel import _
from flask_login import login_required, current_user
from ..models import db, Notification
from ..utils import redirect_back
from . import notification_bp


@notification_bp.route("/")
@login_required
def show():
    page = request.args.get("page", 1, type=int)
    per_page = current_app.config["NOTIFICATIONS_PER_PAGE"]
    notifications = Notification.query.with_parent(current_user)
    pagination = notifications.order_by(Notification.timestamp.desc()).paginate(
        page, per_page
    )
    notifications = pagination.items
    return render_template(
        "main/notifications.html", pagination=pagination, notifications=notifications
    )


@notification_bp.route("/read/<int:id>/", methods=["POST"])
@login_required
def read(id: int):
    # delete notifications directly after reading it
    notification = Notification.query.get_or_404(id)
    if notification.receiver != current_user:
        abort(403)
    db.session.delete(notification)
    db.session.commit()
    return redirect_back()


@notification_bp.route("/read/all/", methods=["POST"])
@login_required
def read_all():
    for notification in current_user.notifications:
        db.session.delete(notification)
    db.session.commit()
    flash(_("All notifications are read."), "success")
    return redirect_back()

flog/templates/main/_post_actions.html
{#
Copyright (c) 2020 Andy Zhou
MIT License
#}
{% if current_user.is_authenticated %}
    <div>
    {% if not current_user.is_collecting(post) %}
    <a class="btn btn-sm btn-success" href="{{ url_for('main.collect_post', id=post.id) }}">
        <i class="bi-heart"></i>
        {{ _("Collect") }}
    </a>
    {% else %}
        <a class="btn btn-sm btn-warning" href="{{ url_for('main.uncollect_post', id=post.id) }}">
            <i class="bi-ban"></i>
            {{ _("Uncollect") }}
         </a>
    {% endif %}
    {% if current_user.is_administrator() or post.author == current_user %}
        <a class="btn btn-sm btn-primary" href="{{ url_for('main.edit_post', id=post.id) }}">
            <i class="bi-pencil-square"></i>
            {{ _("EDIT [ADMIN]") }}
        </a>
    {% endif %}
    {# 如果当前用户是协管员，并且文章作者没有协管员权限时，抑或当前用户是该文章作者时，显示删除按钮 #}
    {% if (current_user.can(Permission.MODERATE)  and not post.author.can(Permission.MODERATE))
        or current_user.is_administrator() or post.author == current_user %}
        <form class="form-inline" method="POST" action="{{ url_for('main.delete_post', id=post.id) }}"
            style="display: inline !important">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
            <button class="btn btn-sm btn-danger" onclick="return confirm('{{ _('Are you sure?') }}');">
                <i class="bi-trash"></i>
                {{ _("DELETE [ADMIN]") }}
                </button>
            </form>
    {% endif %}
    </div>
{% endif %}

flog/templates/main/_sidebar.html
{#
Copyright (c) 2020 Andy Zhou
MIT License
#}
{% from 'macros.html' import action_card %}
<div class="col-md-4">
    {% if current_user.is_authenticated %}
        <div class="card mb-3 d-flex flex-wrap justify-content-between">
            <div class="card-header">{{ _("Quick Actions") }}</div>
            <div class="d-flex flex-fill">
                {{ action_card("bi-images", _("Images"), url_for("image.manage")) }}
                {{ action_card("bi-collection", _("Collections"), url_for("main.collected_posts")) }}
            </div>
        </div>
        <div class="card mb-3 d-flex flex-wrap justify-content-between">
            <div class="card-header">{{ _("Post") }}</div>
            <div class="d-flex flex-fill">
                {{ action_card("bi-vector-pen", _("Write"), url_for("main.write")) }}
                {{ action_card("bi-files", _("Yours"), url_for("main.manage_posts") )}}
            </div>
        </div>
        <div class="card mb-3 d-flex flex-wrap justify-content-between">
            <div class="card-header">{{ _("Group") }}</div>
            <div class="d-flex flex-fill">
                {{ action_card("bi-plus", _("Create"), url_for("group.create")) }}
                {{ action_card("bi-person-plus", _("Join"), url_for("group.explore")) }}
                {{ action_card("bi-diagram-3-fill", _("Yours"), url_for("user.groups")) }}
            </div>
        </div>
        <div class="card mb-3 d-flex flex-wrap justify-content-between">
            <div class="card-header">{{ _("Explore") }}</div>
            <div class="d-flex flex-fill">
                {{ action_card("bi-people", _("Users"), url_for("user.all")) }}
                {{ action_card("bi-diagram-3", _("Groups"), url_for("group.all")) }}
                {{ action_card("bi-stars", _("Picks"), url_for("main.picks")) }}
            </div>
        </div>
        <div class="card mb-3">
            <div class="card-header">{{ _("Profile") }}</div>
            <div class="d-flex flex-fill">
                {{ action_card("bi-person-badge", _("View"), current_user.profile_url()) }}
                {{ action_card("bi-pencil", _("Edit"), url_for("user.edit_profile")) }}
            </div>
        </div>
        <div class="card mb-3">
            <div class="card-header">{{ _("Column") }}</div>
            <div class="d-flex flex-fill">
                {{ action_card("bi-plus", _("Create"), url_for("main.create_column")) }}
                {{ action_card("bi-journals", _("All"), url_for("main.all_columns")) }}
            </div>
        </div>
    {% endif %}
</div>

flog/templates/main/collections.html
{#
Copyright (c) 2020 Andy Zhou
MIT License
#}
{% extends 'base.html' %}
{% from 'macros.html' import post_actions with context %}
{% block title %}{{ _("Your collections") }}{% endblock %}
{% block page_content %}
    <div class="row">
        <div class="col-md-8">
            <ul class="list-group">
                {% if posts | length > 0 %}
                    {% for post in posts %}
                        <li class="list-group-item">
                            <h3 class="text-primary"><a href="{{ url_for('main.full_post', id=post.id) }}">{{ post.title }}</a></h3>
                            <div>
                                {{ post.content | striptags | truncate(200) }}
                                <small class="text-primary">
                                    <a href="{{ url_for('main.full_post', id=post.id) }}">{{ _("Read More") }}</a>
                                </small>
                            </div>
                            {{ post_actions(post) }}
                        </li>
                    {% endfor %}
                {% else %}
                    {{ _("You don't have any collections") }}
                {% endif %}
            </ul>
        </div>
        {% include 'main/_sidebar.html' %}
    </div>
{% endblock page_content %}

flog/templates/main/column.html
{% extends 'base.html' %}
{% from 'macros.html' import post_card with context %}
{% from 'bootstrap/pagination.html' import render_pagination %}
{% block page_content %}
    <h1 class="display-3">{{ column.name }}</h1>
    {% for post in pagination.items %}
        {{ post_card(post) }}
    {% endfor %}
    {{ render_pagination(pagination) }}
{% endblock %}

flog/templates/main/columns.html
{% extends 'base.html' %}
{% from 'macros.html' import column_card with context %}
{% from 'bootstrap/pagination.html' import render_pagination %}
{% block title %}
    All columns
{% endblock title %}
{% block page_content %}
    <div class="row">
        <div class="col-md-8">
            <h1>{{ _("All columns") }}</h1>
            {% for column in pagination.items %}
                {% if column.topped %}
                    {{ column_card(column, "border-warning") }}
                {% else %}
                    {{ column_card(column) }}
                {% endif %}
            {% endfor %}
            {{ render_pagination(pagination) }}
        </div>
        {% include 'main/_sidebar.html' %}
    </div>
{% endblock page_content %}

flog/templates/main/create_column.html
{% extends 'base.html' %}
{% from 'bootstrap/form.html' import render_form %}
{% block page_content %}
    <h1>{{ _("Create Column") }}</h1>
    {{ render_form(form) }}
{% endblock page_content %}

flog/templates/main/edit_post.html
{#
Copyright (c) 2020 Andy Zhou
MIT License
#}
{% extends 'base.html' %}
{% from 'bootstrap/form.html' import render_form %}
{% from 'macros.html' import load_ckeditor with context %}
{% block title %} {{ _("Edit post") }} {% endblock %}
{% block page_content %}
    <h1 class="display-4">{{ _("Edit post") }}</h1>
    {{ render_form(form) }}
{% endblock %}
{% block scripts %}
    {{ super() }}
    {{ load_ckeditor() }}
{% endblock %}

flog/templates/main/full_post.html
{#
Copyright (c) 2020 Andy Zhou
MIT License
#}
{% extends 'base.html' %}
{% from 'macros.html' import post_actions with context %}
{% from 'bootstrap/form.html' import render_form %}
{% from 'bootstrap/pagination.html' import render_pagination %}
{% block title %} Post - {{ post.title }} {% endblock %}
{% block page_content %}
    <div class="row">
        <div class="col-lg-8" style="font-size: large">
            <div class="page-header">
                <h1>
                    {{ post.title }}
                </h1>
                <small>
                    {{ _("Date:") }} {{ moment(post.timestamp).format('LL') }}<br>
                    {{ _("Author:") }}
                    {% if post.author %}
                        <a href="{{ post.author.profile_url() }}" class="profile-popover"
                           data-href="{{ url_for('ajax.get_profile', user_id=post.author.id) }}">
                            {{ post.author.username }}
                        </a>
                    {% else %}
                        {{ _("Deleted Flog User") }}
                    {% endif %}
                </small>
            </div>
            <br>
            <div id="post-content">
                {{ post.content | safe }}
            </div>
            {% if post.columns %}
                <p class="small">
                    {{ _("This post belongs to") }}
                    {% for column in post.columns[:-1] %}
                        <a href="{{ url_for('main.view_column', id=column.id) }}">
                            {{ _("Column") }} 「{{ column.name }}」
                        </a>,
                    {% endfor %}
                    {% if post.columns | length > 1%} {{ _("and") }}{% endif %}
                    <a href="{{ url_for('main.view_column', id=post.columns[-1].id) }}">
                        {{ _("Column") }} 「{{ post.columns[-1].name }}」
                    </a>.
                </p>
            {% endif %}
            {{ post_actions(post, show_collectors=True) }}
            <div class="comments" id="comments">
                {% include 'main/_comments.html' %}
            </div>
        </div>
        {% include 'main/_sidebar.html' %}
    </div>
    {{ ckeditor.load() }}
    {{ ckeditor.config(custom_config="width: 'auto'; height: 30;") }}
{% endblock page_content %}

flog/templates/main/main.html
{#
Copyright (c) 2020 Andy Zhou
MIT License
#}
{% extends 'base.html' %}
{% from 'bootstrap/pagination.html' import render_pagination %}
{% from 'macros.html' import post_card, role_of with context %}
{% block title %}{{ _("Main") }}{% endblock %}
{% block scripts %}
    {{ super() }}
    <script>
        $(document).ready(function () {
            $('.profile-popover').hover(show_profile_popover.bind(this), hide_profile_popover.bind(this));
        })
    </script>
{% endblock scripts %}
{% block page_content %}
    {% if current_user.is_authenticated %}
    <div class="page-header">
        <h1 class="display-4">{{ _("Welcome,") }} {{ role_of(current_user) }} {{ current_user.username }}</h1>
    </div>
    {% endif %}
    <div class="row">
        <div class="col-md-8">
            <ul class="list-group">
            {% for post in posts %}
                {% if (not post.private) or post.author == current_user or current_user.is_administrator() %}
                    {{ post_card(post) }}
                {% endif %}
            {% endfor %}
            </ul>
        </div>
        {% include 'main/_sidebar.html' %}
    </div>
    <div class="pagination">
        {{ render_pagination(pagination) }}
    </div>
{% endblock %}

flog/templates/main/new_post.html
{#
Copyright (c) 2020 Andy Zhou
MIT License
#}
{% extends 'base.html' %}
{% from 'bootstrap/form.html' import render_form %}
{% from 'macros.html' import load_ckeditor with context %}
{% block title %}{{ _("Create Post") }}{% endblock %}
{% block page_content %}
    <h1 class="display-4">{{ _("New Post") }}</h1>
    {{ render_form(form) }}
{% endblock %}
{% block scripts %}
    {{ super() }}
    {{ load_ckeditor() }}
{% endblock scripts %}

flog/templates/main/notifications.html
{#
Copyright (c) 2020 Andy Zhou
MIT License
#}
{% extends 'base.html' %}
{% block page_content %}
    <div class="nav nav-pills" role="tablist">
        <a class="nav-item nav-link {% if request.args.get('filter') != 'unread' %}active{% endif %}"
           href="{{ url_for('notification.show', filter='all') }}">
           <i class="bi-inbox"></i>
           {{ _("All") }}
        </a>
        <form method="POST" action="{{ url_for('notification.read_all') }}">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
            <button class="btn btn-sm btn-light">
                <i class="bi-envelope-open-fill"></i>
                {{ _("Mark all as read") }}
            </button>
        </form>
    </div>
    <ul class="list-group">
        {% for notification in notifications %}
            <li class="list-group-item d-flex">
                <div class="p-2 flex-grow-1">
                    {{ _(notification.message) | safe }}
                </div>
                <form class="form-inline p-1" method="POST" action="{{ url_for('notification.read', id=notification.id) }}">
                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                    <button class="btn btn-sm btn-light">
                        <i class="bi-envelope-open"></i>
                        {{ _("Mark as read") }}
                    </button>
                </form>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

flog/templates/main/personal_posts.html
{#
Copyright (c) 2020 Andy Zhou
MIT License
#}
{% extends 'base.html' %}
{% from 'bootstrap/pagination.html' import render_pagination %}
{% from 'macros.html' import post_actions with context %}
{% block title %}Your posts{% endblock %}
{% block page_content %}
    <div class="row">
    <div class="col-lg-8">
        <ul class="list-group">
        {% if pagination.items | length > 0 %}
            {% for post in pagination.items %}
                <li class="list-group-item">
                    <a href="{{ post.url() }}">{{ post.title }}</a>
                    <p>
                        {{ post.content | striptags | truncate(200) }}
                    </p>
                    <span class="float-right">
                        {{ post_actions(post) }}
                    </span>
            {% endfor %}
        {% else %}
            <p class="display-4">{{ _("Nothing Here") }}</p>
        {% endif %}
        </ul>
        {{ render_pagination(pagination) }}
    </div>
    {% include 'main/_sidebar.html' %}
    </div>
{% endblock page_content %}

flog/templates/main/picked.html
{#
Copyright (c) 2020 Andy Zhou
MIT License
#}
{% extends 'base.html' %}
{% from 'macros.html' import post_actions with context %}
{% block title %}{{ _("Your collections") }}{% endblock %}
{% block page_content %}
    <div class="row">
        <div class="col-md-8">
            <ul class="list-group">
                {% if posts | length > 0 %}
                    {% for post in posts %}
                        <li class="list-group-item">
                            <h3 class="text-primary"><a href="{{ url_for('main.full_post', id=post.id) }}">{{ post.title }}</a></h3>
                            <div>
                                {{ post.content | striptags | truncate(200) }}
                                <small class="text-primary">
                                    <a href="{{ url_for('main.full_post', id=post.id) }}">{{ _("Read More") }}</a>
                                </small>
                            </div>
                            {{ post_actions(post) }}
                        </li>
                    {% endfor %}
                {% else %}
                    {{ _("There are no picked posts.") }}
                {% endif %}
            </ul>
        </div>
        {% include 'main/_sidebar.html' %}
    </div>
{% endblock page_content %}

flog/templates/main/search.html
{% extends 'base.html' %}
{% from 'bootstrap/pagination.html' import render_pagination %}
{% from 'macros.html' import user_card, post_card, group_card, column_card with context %}
{% block title %}Flog - Seach: {{ q }}{% endblock %}
{% block search_bar %}
    <form class="form-inline my-2 my-lg-0" action="{{ url_for('main.search', category=category) }}">
        <input type="text" name="q" class="form-control mr-sm-1"
                placeholder="{{ _('Search user, post or group') }}"
            required>
        <input type="hidden" name="category" value="{{ category }}">
        <button class="btn btn-light my-2 my-sm-0" type="submit">
            <span class="bi-search"></span>
        </button>
    </form>
{% endblock %}
{% block page_content %}
    <div class="page-header">
        <h1 class="display-4">Search: <em>{{ q }}</em></h1>
    </div>
    <div class="row">
        <div class="col-md-3">
            <div class="nav nav-pills flex-column" role="tablist" aria-orientation="vertical">
                <a class="nav-item nav-link {% if category == 'post' %}active{% endif %}"
                   href="{{ url_for('.search', q=q, category='post') }}">
                   {{ _("Post") }}
                </a>
                <a class="nav-item nav-link {% if category == 'user' %}active{% endif %}"
                   href="{{ url_for('.search', q=q, category='user') }}">
                   {{ _("User") }}
                </a>
                <a class="nav-item nav-link {% if category == 'group' %}active{% endif %}"
                   href="{{ url_for('.search', q=q, category='group') }}">
                   {{ _("Group") }}
                </a>
                <a class="nav-item nav-link {% if category == 'column' %}active{% endif %}"
                   href="{{ url_for('.search', q=q, category='column') }}">
                    {{ _("Column") }}
                </a>
            </div>
        </div>
        <div class="col-md-9">
            {% if results %}
                <h5>
                    {{ results_count }}
                    {{ ngettext('result', 'results', __num=results|length) }}
                </h5>
                {% for item in results %}
                    {% if category == 'user' %}
                        {{ user_card(item) }}
                    {% elif category == 'group' %}
                        {{ group_card(item) }}
                    {% elif category == 'column' %}
                        {{ column_card(item) }}
                    {% else %}
                        {{ post_card(item) }}
                    {% endif %}
                {% endfor %}
                {{ render_pagination(pagination) }}
            {% else %}
                <h5 class="tip">{{ _("No results") }}</h5>
            {% endif %}
        </div>
    </div>
{% endblock page_content %}